import Head from "next/head";
import NavBar from "./components/Nav/NavBar";
import Portada from "./components/Index/Portada";
import About1 from "./components/Index/About1";
import About2 from "./components/Index/About2";
import Verciones from "./components/Index/Verciones";
import Footer from "./components/Index/Footer";
import style from "@/styles/index.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>ElectronPlayer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <NavBar />
      <main className={style.main}>
        <div>
          <main>
            <section>
              <Portada />
              <About1 />
              <About2 />
              <Verciones />
            </section>
          </main>
        </div>
      </main>
      <footer>
        <Footer />
      </footer>
    </>
  );
}
