import Head from "next/head";
import NavBar from "@/components/Nav/NavBar";
import Portada from "@/components/Index/Portada";
import About1 from "@/components/Index/About1";
import About2 from "@/components/Index/About2";
import Verciones from "@/components/Index/Verciones";
import Footer from "@/components/Index/Footer";
import style from "@/styles/index/Index.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>ElectronPlayer | Reproductor de Musica Gratis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
        <meta
          name="description"
          content="ElectronPlayer es el reproductor de música gratuito. Escucha musica de manera local sin conexion a internet o bien descarga la musica que mas te guste"
        ></meta>
        <meta
          property="og:title"
          content="ElectronPlayer - Reproductor de música gratuito"
        ></meta>
        <meta
          property="og:description"
          content="ElectronPlayer es el reproductor de música gratuito. Escucha musica de manera local sin conexion a internet o bien descarga la musica que mas te guste"
        ></meta>
        <meta
          name="keywords"
          content="Reproductor de música, Descarga de música, Reproducción de música offline, Aplicación de reproductor de música, Biblioteca de música local, Música gratis para descargar, Descargar música MP3, Almacenamiento de música local, Aplicación de música para PC, Reproductor de música para Windows, ElectronPlayer"
        ></meta>
      </Head>
      <NavBar />
      <main className={style.main}>
        <div>
          <main>
            <section>
              <Portada />
              <About1 />
              <About2 />
              <Verciones />
            </section>
          </main>
        </div>
      </main>
      <footer>
        <Footer />
      </footer>
    </>
  );
}
