import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import NavBar from "./components/Index/NavBar";
import Portada from "./components/Index/Portada";
import About1 from "./components/Index/About1";
import About2 from "./components/Index/About2";
import Verciones from "./components/Index/Verciones";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <NavBar />
      <main>
        <div>
          <main>
            <section>
              <Portada />
              <About1 />
              <About2 />
              <Verciones />
            </section>
          </main>
        </div>
      </main>
    </>
  );
}
